server:
  port: 8081

spring:
  application:
    name: dify-llm-service

modelProvider:
  llm:
    service-url: http://localhost:8089
    action: /api/provider/unified/chat/stream

# Feign 超时配置（必须）
feign:
  client:
    config:
      default:
        connectTimeout: 30000      # 连接超时 30秒（与你 RestTemplate 保持一致）
        readTimeout: 600000        # 读取超时 600秒（与你 RestTemplate 保持一致）

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/  # 注册到中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
