server:
  port: 8081

spring:
  application:
    name: dify-llm-service

modelProvider:
  llm:
    service-url: http://dify-model-provider:8089
    action: /api/provider/unified/chat/stream


# Feign 超时配置（解决 Read timed out）
feign:
  client:
    config:
      default:
        connectTimeout: 300000    # 5分钟
        readTimeout: 1200000      # 20分钟！足够模型推理

eureka:
  client:
    serviceUrl:
      defaultZone: http://dify-eureka-server:8085/eureka/  # 注册到中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}