server:
  port: 8083

spring:
  application:
    name: dify-function-service

# 自定义配置：本地模型 + 向量库 + 服务地址（Day6 核心配置）
dify:
  # 微服务内部调用地址
  service:
    rag: http://localhost:8082

# 函数注册配置（自动加载的内置函数）
function:
  enable-default-functions: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/  # 注册到中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


