server:
  port: 8083

spring:
  application:
    name: dify-function-service

# 搜索引擎查询内容
web-search:
  enabled: true  # matchIfMissing=true 表示不配置时默认为 true
  searxng:
    url: http://localhost:8002

# 函数注册配置（自动加载的内置函数）
function:
  enable-default-functions: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/  # 注册到中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


