server:
  port: 8088
spring:
  application:
    name: dify-workflow-service
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  # 必须配置！让JdbcTemplate可用
  jdbc:
    template:
      query-timeout: 3
  # 生产级 Redis 配置（你的 docker redis）
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    cloud:
      loadbalancer:
        enabled: true

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/  # 注册到中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Feign 超时配置（解决 Read timed out）
feign:
  client:
    config:
      default:
        connectTimeout: 600000    # 10分钟
        readTimeout: 1200000      # 20分钟！足够模型推理

logging:
  level:
    com.dify: DEBUG